#Setting:
#Expiration         --> 本地文件超时时间
#CheckExpiration    --> 检查本地文件是否超时的频率
#Common             --> 本地存放Module的路径
#ReserveSize        --> 磁盘空间小于预留大小 不再接受备份

#Database:
#Host               --> 数据库主机地址
#Port               --> 数据库主机端口
#Username           --> 用户名
#Password           --> 密码

#Backup:
#Host               --> 备份服务器的GRPC主机地址
#Port               --> 备份服务器的GRPC端口号

Setting:
  Expiration: 180
  CheckExpiration: 24
  Common: C:\Backserver\common
  ReserveSize: 121213121


Database:
  Host: localhost
  Port: 3306
  Username: root
  Password: Qaqaqa00.0

GRPC:
  Port: 9999