// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: grpc/ModuleBalancing.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Serveraddress string                 `protobuf:"bytes,1,opt,name=serveraddress,proto3" json:"serveraddress,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleDownloadRequest) Reset() {
	*x = ModuleDownloadRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleDownloadRequest) ProtoMessage() {}

func (x *ModuleDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleDownloadRequest.ProtoReflect.Descriptor instead.
func (*ModuleDownloadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleDownloadRequest) GetServeraddress() string {
	if x != nil {
		return x.Serveraddress
	}
	return ""
}

func (x *ModuleDownloadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ModuleDownloadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ModulePushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModulePushResponse) Reset() {
	*x = ModulePushResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModulePushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModulePushResponse) ProtoMessage() {}

func (x *ModulePushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModulePushResponse.ProtoReflect.Descriptor instead.
func (*ModulePushResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{1}
}

func (x *ModulePushResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ModulePushResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadRequest_Information
	//	*UploadRequest_ChunkData
	Data          isUploadRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{2}
}

func (x *UploadRequest) GetData() isUploadRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadRequest) GetInformation() *Finformation {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_Information); ok {
			return x.Information
		}
	}
	return nil
}

func (x *UploadRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadRequest_Data interface {
	isUploadRequest_Data()
}

type UploadRequest_Information struct {
	Information *Finformation `protobuf:"bytes,1,opt,name=information,proto3,oneof"`
}

type UploadRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadRequest_Information) isUploadRequest_Data() {}

func (*UploadRequest_ChunkData) isUploadRequest_Data() {}

type Finformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Crc64         string                 `protobuf:"bytes,3,opt,name=crc64,proto3" json:"crc64,omitempty"`
	MUnix         string                 `protobuf:"bytes,4,opt,name=MUnix,proto3" json:"MUnix,omitempty"`
	CUnix         string                 `protobuf:"bytes,5,opt,name=CUnix,proto3" json:"CUnix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finformation) Reset() {
	*x = Finformation{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finformation) ProtoMessage() {}

func (x *Finformation) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finformation.ProtoReflect.Descriptor instead.
func (*Finformation) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{3}
}

func (x *Finformation) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Finformation) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Finformation) GetCrc64() string {
	if x != nil {
		return x.Crc64
	}
	return ""
}

func (x *Finformation) GetMUnix() string {
	if x != nil {
		return x.MUnix
	}
	return ""
}

func (x *Finformation) GetCUnix() string {
	if x != nil {
		return x.CUnix
	}
	return ""
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ModuleBalancing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_grpc_ModuleBalancing_proto_rawDescGZIP(), []int{4}
}

func (x *UploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_grpc_ModuleBalancing_proto protoreflect.FileDescriptor

const file_grpc_ModuleBalancing_proto_rawDesc = "" +
	"\n" +
	"\x1agrpc/ModuleBalancing.proto\x12\x0fModuleBalancing\"q\n" +
	"\x15ModuleDownloadRequest\x12$\n" +
	"\rserveraddress\x18\x01 \x01(\tR\rserveraddress\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"L\n" +
	"\x12ModulePushResponse\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\"{\n" +
	"\rUploadRequest\x12A\n" +
	"\vinformation\x18\x01 \x01(\v2\x1d.ModuleBalancing.finformationH\x00R\vinformation\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"\x80\x01\n" +
	"\ffinformation\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12\x14\n" +
	"\x05crc64\x18\x03 \x01(\tR\x05crc64\x12\x14\n" +
	"\x05MUnix\x18\x04 \x01(\tR\x05MUnix\x12\x14\n" +
	"\x05CUnix\x18\x05 \x01(\tR\x05CUnix\"D\n" +
	"\x0eUploadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\xac\x01\n" +
	"\x06Module\x12K\n" +
	"\x06Upload\x12\x1e.ModuleBalancing.UploadRequest\x1a\x1f.ModuleBalancing.UploadResponse(\x01\x12U\n" +
	"\x04Push\x12&.ModuleBalancing.ModuleDownloadRequest\x1a#.ModuleBalancing.ModulePushResponse0\x01B\aZ\x05/grpcb\x06proto3"

var (
	file_grpc_ModuleBalancing_proto_rawDescOnce sync.Once
	file_grpc_ModuleBalancing_proto_rawDescData []byte
)

func file_grpc_ModuleBalancing_proto_rawDescGZIP() []byte {
	file_grpc_ModuleBalancing_proto_rawDescOnce.Do(func() {
		file_grpc_ModuleBalancing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_ModuleBalancing_proto_rawDesc), len(file_grpc_ModuleBalancing_proto_rawDesc)))
	})
	return file_grpc_ModuleBalancing_proto_rawDescData
}

var file_grpc_ModuleBalancing_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_ModuleBalancing_proto_goTypes = []any{
	(*ModuleDownloadRequest)(nil), // 0: ModuleBalancing.ModuleDownloadRequest
	(*ModulePushResponse)(nil),    // 1: ModuleBalancing.ModulePushResponse
	(*UploadRequest)(nil),         // 2: ModuleBalancing.UploadRequest
	(*Finformation)(nil),          // 3: ModuleBalancing.finformation
	(*UploadResponse)(nil),        // 4: ModuleBalancing.UploadResponse
}
var file_grpc_ModuleBalancing_proto_depIdxs = []int32{
	3, // 0: ModuleBalancing.UploadRequest.information:type_name -> ModuleBalancing.finformation
	2, // 1: ModuleBalancing.Module.Upload:input_type -> ModuleBalancing.UploadRequest
	0, // 2: ModuleBalancing.Module.Push:input_type -> ModuleBalancing.ModuleDownloadRequest
	4, // 3: ModuleBalancing.Module.Upload:output_type -> ModuleBalancing.UploadResponse
	1, // 4: ModuleBalancing.Module.Push:output_type -> ModuleBalancing.ModulePushResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_ModuleBalancing_proto_init() }
func file_grpc_ModuleBalancing_proto_init() {
	if File_grpc_ModuleBalancing_proto != nil {
		return
	}
	file_grpc_ModuleBalancing_proto_msgTypes[2].OneofWrappers = []any{
		(*UploadRequest_Information)(nil),
		(*UploadRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_ModuleBalancing_proto_rawDesc), len(file_grpc_ModuleBalancing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_ModuleBalancing_proto_goTypes,
		DependencyIndexes: file_grpc_ModuleBalancing_proto_depIdxs,
		MessageInfos:      file_grpc_ModuleBalancing_proto_msgTypes,
	}.Build()
	File_grpc_ModuleBalancing_proto = out.File
	file_grpc_ModuleBalancing_proto_goTypes = nil
	file_grpc_ModuleBalancing_proto_depIdxs = nil
}
