// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0--rc1
// source: grpc/ModuleBalancing.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Module_Upload_FullMethodName       = "/ModuleBalancing.Module/Upload"
	Module_Push_FullMethodName         = "/ModuleBalancing.Module/Push"
	Module_ModuleReload_FullMethodName = "/ModuleBalancing.Module/ModuleReload"
	Module_AllowStorage_FullMethodName = "/ModuleBalancing.Module/AllowStorage"
)

// ModuleClient is the client API for Module service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModuleClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error)
	Push(ctx context.Context, in *ModuleDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ModulePushResponse], error)
	ModuleReload(ctx context.Context, in *ModuleReloadRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	AllowStorage(ctx context.Context, in *AllowStorageRequest, opts ...grpc.CallOption) (*AllowStorageResponse, error)
}

type moduleClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleClient(cc grpc.ClientConnInterface) ModuleClient {
	return &moduleClient{cc}
}

func (c *moduleClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Module_ServiceDesc.Streams[0], Module_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadRequest, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Module_UploadClient = grpc.ClientStreamingClient[UploadRequest, UploadResponse]

func (c *moduleClient) Push(ctx context.Context, in *ModuleDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ModulePushResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Module_ServiceDesc.Streams[1], Module_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ModuleDownloadRequest, ModulePushResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Module_PushClient = grpc.ServerStreamingClient[ModulePushResponse]

func (c *moduleClient) ModuleReload(ctx context.Context, in *ModuleReloadRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Module_ModuleReload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleClient) AllowStorage(ctx context.Context, in *AllowStorageRequest, opts ...grpc.CallOption) (*AllowStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllowStorageResponse)
	err := c.cc.Invoke(ctx, Module_AllowStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServer is the server API for Module service.
// All implementations must embed UnimplementedModuleServer
// for forward compatibility.
type ModuleServer interface {
	Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error
	Push(*ModuleDownloadRequest, grpc.ServerStreamingServer[ModulePushResponse]) error
	ModuleReload(context.Context, *ModuleReloadRequest) (*EmptyResponse, error)
	AllowStorage(context.Context, *AllowStorageRequest) (*AllowStorageResponse, error)
	mustEmbedUnimplementedModuleServer()
}

// UnimplementedModuleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModuleServer struct{}

func (UnimplementedModuleServer) Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedModuleServer) Push(*ModuleDownloadRequest, grpc.ServerStreamingServer[ModulePushResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedModuleServer) ModuleReload(context.Context, *ModuleReloadRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModuleReload not implemented")
}
func (UnimplementedModuleServer) AllowStorage(context.Context, *AllowStorageRequest) (*AllowStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowStorage not implemented")
}
func (UnimplementedModuleServer) mustEmbedUnimplementedModuleServer() {}
func (UnimplementedModuleServer) testEmbeddedByValue()                {}

// UnsafeModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleServer will
// result in compilation errors.
type UnsafeModuleServer interface {
	mustEmbedUnimplementedModuleServer()
}

func RegisterModuleServer(s grpc.ServiceRegistrar, srv ModuleServer) {
	// If the following call pancis, it indicates UnimplementedModuleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Module_ServiceDesc, srv)
}

func _Module_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ModuleServer).Upload(&grpc.GenericServerStream[UploadRequest, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Module_UploadServer = grpc.ClientStreamingServer[UploadRequest, UploadResponse]

func _Module_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ModuleDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModuleServer).Push(m, &grpc.GenericServerStream[ModuleDownloadRequest, ModulePushResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Module_PushServer = grpc.ServerStreamingServer[ModulePushResponse]

func _Module_ModuleReload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).ModuleReload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Module_ModuleReload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).ModuleReload(ctx, req.(*ModuleReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Module_AllowStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).AllowStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Module_AllowStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).AllowStorage(ctx, req.(*AllowStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Module_ServiceDesc is the grpc.ServiceDesc for Module service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Module_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ModuleBalancing.Module",
	HandlerType: (*ModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModuleReload",
			Handler:    _Module_ModuleReload_Handler,
		},
		{
			MethodName: "AllowStorage",
			Handler:    _Module_AllowStorage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _Module_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Push",
			Handler:       _Module_Push_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/ModuleBalancing.proto",
}
